---
app_name: billing-engine
httpport: 8080
db:
    master:
        maxidle: 10
        maxopen: 50
        user: "root"
        pass: ""
        host: "localhost"
        port: 3306
        name: "billing_engine_db"