---
app_name: billing-engine
httpport: 8080
db:
    master:
        maxidle: 10
        maxopen: 50
        user: "user_be"
        pass: "secret"
        host: "host"
        port: 6606
        name: "db_name"